project_id = "tiqkfmokjrmoyytqmhat"

[functions.send-confirmation]
verify_jwt = false

[functions.send-signup-notification]
verify_jwt = false

[functions.test-email]
verify_jwt = false

[auth]
[auth.email]
enable_signup = true
double_confirm_change_email = false
enable_confirmations = false
template = { confirm_signup = "send-confirmation" }

# Webhook configuration for custom emails
[webhooks.send_email]
enabled = true
url = "https://tiqkfmokjrmoyytqmhat.supabase.co/functions/v1/send-confirmation"
events = ["user.signup", "user.confirmation_requested"]