project_id = "tiqkfmokjrmoyytqmhat"

[functions.send-confirmation]
verify_jwt = false

[functions.send-signup-notification]
verify_jwt = false

[functions.test-email]
verify_jwt = false

[auth]
[auth.email]
enable_signup = true
double_confirm_change_email = false
enable_confirmations = true

[auth.email.template]
[auth.email.template.confirmation]
subject = "Welcome to The Transhumanist Forum - Confirm Your Account"
content_path = "./supabase/functions/send-confirmation/index.ts"

[auth.email.smtp]
host = "smtp.resend.com"
port = 587
user = "resend"
admin_email = "noreply@resend.dev"
max_frequency = 3600