// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tiqkfmokjrmoyytqmhat.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRpcWtmbW9ranJtb3l5dHFtaGF0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTYwNTMxNTksImV4cCI6MjA3MTYyOTE1OX0.naVw0WVqU5X1b7_kudxmdhcxxWcgDjTL2HiWyAiInhQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});